### ISSUE TITLE
Captain's Parrot crash

### ISSUE THREAD

**Issue by jleclanche** [jleclanche/fireplace#100]
```pytb
DEBUG:root:<Minion ("Captain's Parrot")> moves from <Zone.HAND: 3> to <Zone.PLAY: 1>
INFO:root:Activating <Minion ("Captain's Parrot")> action targeting None
INFO:root:<Minion ("Captain's Parrot")> triggering <TargetedAction: ForceDraw(CARDS=<Selector: DECK FRIENDLY and PIRATE and>)> targeting [Player(name='Player2', hero=<Hero ('Garrosh Hellscream')>)]
Traceback (most recent call last):
  File "./full_game.py", line 54, in <module>
    main()
  File "./full_game.py", line 41, in main
    card.play()
  File "../fireplace/card.py", line 312, in play
    self.game.queue_actions(self.controller, [Play(self, target, choose)])
  File "../fireplace/game.py", line 195, in queue_actions
    ret.append(action.trigger(source))
  File "../fireplace/actions.py", line 108, in trigger
    self.do(source, *args)
  File "../fireplace/actions.py", line 231, in do
    card.action()
  File "../fireplace/card.py", line 224, in action
    self.game.queue_actions(self, actions)
  File "../fireplace/game.py", line 195, in queue_actions
    ret.append(action.trigger(source))
  File "../fireplace/actions.py", line 314, in trigger
    ret.append(self.do(source, target, *target_args))
TypeError: do() takes 3 positional arguments but 4 were given
```

**Comment by jleclanche** [comment]
@beheh Want to take this one?

**Comment by beheh** [comment]
I'll take a look.
