### ISSUE TITLE
Millhouse crash

### ISSUE THREAD

**Issue by jleclanche** [jleclanche/fireplace#143]
```
INFO:root:<Enchantment ('Kill Millhouse!')> triggers off <Action: BeginTurn(PLAYER=Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>))> from BaseGame(players=[Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>), Player(name='Player2', hero=<Hero ('Thrall')>)])
INFO:root:<Enchantment ('Kill Millhouse!')> triggering <TargetedAction: Destroy()> targeting [<Enchantment ('Kill Millhouse!')>]
----------------------------------------
Exception happened during processing of request from ('68.35.155.67', 42885)
Traceback (most recent call last):
  File "/usr/lib/python3.4/socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.4/socketserver.py", line 673, in __init__
    self.handle()
  File "./kettle.py", line 264, in handle
    manager.process_send_option(packet["SendOption"])
  File "./kettle.py", line 181, in process_send_option
    self.game.end_turn()
  File "/home/adys/src/git/fireplace/fireplace/game.py", line 249, in end_turn
    return self.queue_actions(self, [EndTurn(self.current_player)])
  File "/home/adys/src/git/fireplace/fireplace/game.py", line 197, in queue_actions
    ret.append(action.trigger(source))
  File "/home/adys/src/git/fireplace/fireplace/actions.py", line 108, in trigger
    self.do(source, *args)
  File "/home/adys/src/git/fireplace/fireplace/actions.py", line 186, in do
    source.game._end_turn()
  File "/home/adys/src/git/fireplace/fireplace/game.py", line 264, in _end_turn
    self.begin_turn(self.current_player.opponent)
  File "/home/adys/src/git/fireplace/fireplace/game.py", line 267, in begin_turn
    return self.queue_actions(self, [BeginTurn(player)])
  File "/home/adys/src/git/fireplace/fireplace/game.py", line 197, in queue_actions
    ret.append(action.trigger(source))
  File "/home/adys/src/git/fireplace/fireplace/actions.py", line 108, in trigger
    self.do(source, *args)
  File "/home/adys/src/git/fireplace/fireplace/actions.py", line 147, in do
    self.broadcast(source, EventListener.ON, player)
  File "/home/adys/src/git/fireplace/fireplace/actions.py", line 87, in broadcast
    self._broadcast(entity, source, at, *args)
  File "/home/adys/src/git/fireplace/fireplace/actions.py", line 80, in _broadcast
    entity.trigger_event(source, event, args)
  File "/home/adys/src/git/fireplace/fireplace/entity.py", line 56, in trigger_event
    source.game.queue_actions(self, actions)
  File "/home/adys/src/git/fireplace/fireplace/game.py", line 197, in queue_actions
    ret.append(action.trigger(source))
  File "/home/adys/src/git/fireplace/fireplace/actions.py", line 338, in trigger
    ret.append(self.do(source, target, *target_args))
  File "/home/adys/src/git/fireplace/fireplace/actions.py", line 408, in do
    target._destroy()
  File "/home/adys/src/git/fireplace/fireplace/card.py", line 704, in destroy
    logging.info("Destroying buff %r from %r" % (self, self.owner))
AttributeError: 'Enchantment' object has no attribute 'owner'
----------------------------------------
```

**Comment by jleclanche** [comment]
I think this was a nonissue related to getting an Enchantment card in hand.
