### ISSUE TITLE
AttributeError with ShadowForm

### ISSUE THREAD

**Issue by liujimj** [jleclanche/fireplace#197]
Not quite sure why I'm seeing this error. I'm synced to head, just ran bootstrap.sh to generate fresh card defs as well.

```pytb
PS C:\Users\liuji\Google Drive\GitHubVisualStudio\fireplace\tests> py -3 .\test_main.py
Traceback (most recent call last):
 File ".\test_main.py", line 2, in <module>
  from utils import *
  File "C:\Users\liuji\Google Drive\GitHubVisualStudio\fireplace\tests\utils.py", line 3, in <module>
    import fireplace.cards
  File "..\fireplace\cards\__init__.py", line 4, in <module>
    from .blackrock import *
  File "..\fireplace\cards\blackrock\__init__.py", line 1, in <module>
    from .adventure import *
  File "..\fireplace\cards\blackrock\adventure.py", line 1, in <module>
    from ..utils import *
  File "..\fireplace\cards\utils.py", line 4, in <module>
    from ..aura import Refresh
  File "..\fireplace\aura.py", line 1, in <module>
    from .managers import CardManager
  File "..\fireplace\managers.py", line 168, in <module>
    GameTag.SHADOWFORM: "shadowform",
  File "C:\Program Files (x86)\Python 3.5\lib\enum.py", line 268, in __getattr__
    raise AttributeError(name) from None
 AttributeError: SHADOWFORM
```

**Comment by jleclanche** [comment]
Run `pip install --upgrade 
-e git+https://github.com/HearthSim/python-hearthstone.git#egg=hearthstone` to update python-hearthstone
