### ISSUE TITLE
Windows install of fireplace

### ISSUE THREAD

**Issue by brownto** [jleclanche/fireplace#243]
I have installed the fireplace and hearthstone modules from downloaded zip files with two python setup.py install. When I try to run the 
full_game.py file it gives the following error. Not sure how to create the fireplace-0.1-py3.4.egg\\fireplace\\CardDefs.xml' file with bootstrap. Any help would be greatly appreciated.

Thanks

Tom
```
[fireplace.__init__]: Initializing card database
Traceback (most recent call last):
  File "C:\Python34_64bit\fireplace\fireplace-master\tests\full_game.py", line 57, in <module>
    main()
  File "C:\Python34_64bit\fireplace\fireplace-master\tests\full_game.py", line 11, in main
    deck1 = random_draft(hero=MAGE)
  File "C:\Python34_64bit\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\utils.py", line 72, in random_draft
    hero = cards.db[hero]
  File "C:\Python34_64bit\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\cards\__init__.py", line 16, in __getitem__
    self.initialize()
  File "C:\Python34_64bit\lib\site-packages\fireplace-0.1-py3.4.egg\fireplace\cards\__init__.py", line 42, in initialize
    raise RuntimeError("%r does not exist. Create it with `bootstrap`." % (self.filename))
RuntimeError: 'C:\\Python34_64bit\\lib\\site-packages\\fireplace-0.1-py3.4.egg\\fireplace\\CardDefs.xml' does not exist. Create it with `bootstrap`.
```

**Comment by jleclanche** [comment]
Have you run the `bootstrap` script as explained in the README?
