### ISSUE TITLE
Imp-losion gives an error when targeting Divine Shield

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#259]
`TypeError: 'NoneType' object cannot be interpreted as an integer`

```python
Traceback (most recent call last):
  File "./test_fuzzy.py", line 70, in main
  File "/home/benedict/Dokumente/fireplace/fireplace/card.py", line 299, in play
    self.game.queue_actions(self.controller, [actions.Play(self, target, index)])
  File "/home/benedict/Dokumente/fireplace/fireplace/game.py", line 160, in queue_actions
    ret = self.trigger_actions(source, actions)
  File "/home/benedict/Dokumente/fireplace/fireplace/game.py", line 184, in trigger_actions
    ret.append(action.trigger(source))
  File "/home/benedict/Dokumente/fireplace/fireplace/actions.py", line 127, in trigger
    self.do(source, *args)
  File "/home/benedict/Dokumente/fireplace/fireplace/actions.py", line 314, in do
    play_action()
  File "/home/benedict/Dokumente/fireplace/fireplace/card.py", line 199, in action
    self.game.queue_actions(source, _actions)
  File "/home/benedict/Dokumente/fireplace/fireplace/game.py", line 160, in queue_actions
    ret = self.trigger_actions(source, actions)
  File "/home/benedict/Dokumente/fireplace/fireplace/game.py", line 184, in trigger_actions
    ret.append(action.trigger(source))
  File "/home/benedict/Dokumente/fireplace/fireplace/actions.py", line 437, in trigger
    source = source[0]
```

[Full log](https://gist.github.com/beheh/4ee544b004b0a7d41ebf).

**Comment by jleclanche** [comment]
Test?

**Comment by beheh** [comment]
You can pull from `test_implosion_divine_shield` from my fork or here:

```python
def test_implosion_divine_shield():
	game = prepare_game()
	wisp = game.player1.give(WISP)
	wisp.play()
	game.player1.give(HAND_OF_PROTECTION).play(target=wisp)
	assert wisp.divine_shield
	implosion = game.player1.give("GVG_045")
	implosion.play(target=wisp)
	assert not wisp.dead
	assert not wisp.divine_shield
	assert len(game.player1.field) == 1
```
