### ISSUE TITLE
Black Knight crash

### ISSUE THREAD

**Issue by jleclanche** [jleclanche/fireplace#267]
```pytb
[fireplace.card]: <Minion ('The Beast')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
Playing <Minion ('Reckless Rocketeer')> on None
[fireplace.entity]: Player1 plays <Minion ('Reckless Rocketeer')>
[fireplace.card]: <Minion ('Reckless Rocketeer')> moves from <Zone.HAND: 3> to <Zone.PLAY: 1>
[fireplace.actions]: <Minion ('Reckless Rocketeer')> triggering <TargetedAction: Battlecry()> targeting [<Minion ('Reckless Rocketeer')>]
[fireplace.actions]: Activating <Minion ('Reckless Rocketeer')> action targeting None
Playing <Secret ('Ice Block')> on None
[fireplace.entity]: Player1 plays <Secret ('Ice Block')>
[fireplace.card]: <Secret ('Ice Block')> moves from <Zone.HAND: 3> to <Zone.SECRET: 7>
[fireplace.actions]: <Secret ('Ice Block')> triggering <TargetedAction: Battlecry()> targeting [<Secret ('Ice Block')>]
[fireplace.actions]: Activating <Secret ('Ice Block')> action targeting None
[fireplace.actions]: <Minion ('Majordomo Executus')> attacks <Minion ('Slime')>
[fireplace.actions]: <Minion ('Majordomo Executus')> triggering <TargetedAction: Hit(AMOUNT=9)> targeting [<Minion ('Slime')>]
[fireplace.actions]: <Minion ('Majordomo Executus')> triggering <TargetedAction: Predamage(AMOUNT=9)> targeting [<Minion ('Slime')>]
[fireplace.actions]: <Minion ('Majordomo Executus')> triggering <TargetedAction: Damage(AMOUNT=9)> targeting [<Minion ('Slime')>]
[fireplace.actions]: <Minion ('Slime')> triggering <TargetedAction: Hit(AMOUNT=1)> targeting [<Minion ('Majordomo Executus')>]
[fireplace.actions]: <Minion ('Slime')> triggering <TargetedAction: Predamage(AMOUNT=1)> targeting [<Minion ('Majordomo Executus')>]
[fireplace.actions]: <Minion ('Slime')> triggering <TargetedAction: Damage(AMOUNT=1)> targeting [<Minion ('Majordomo Executus')>]
[fireplace.game]: Scheduling death for <Minion ('Majordomo Executus')>
[fireplace.entity]: <Minion ('Majordomo Executus')> is removed from the field
[fireplace.card]: <Minion ('Majordomo Executus')> moves from <Zone.PLAY: 1> to <Zone.GRAVEYARD: 4>
[fireplace.game]: Scheduling death for <Minion ('Slime')>
[fireplace.entity]: <Minion ('Slime')> is removed from the field
[fireplace.card]: <Minion ('Slime')> moves from <Zone.PLAY: 1> to <Zone.GRAVEYARD: 4>
[fireplace.actions]: Processing Death for <Minion ('Majordomo Executus')>
[fireplace.actions]: Game(players=(Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>), Player(name='Player2', hero=<Hero ('Ragnaros the Firelord')>))) triggering <TargetedAction: Deathrattle()> targeting [<Minion ('Majordomo Executus')>]
[fireplace.actions]: <Minion ('Majordomo Executus')> triggering <TargetedAction: Summon(CARDS='BRM_027h')> targeting [Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>)]
[fireplace.actions]: Player1 summons [<Hero ('Ragnaros the Firelord')>]
[fireplace.actions]: Player(name='Player1', hero=<Hero ('Ragnaros the Firelord')>) triggering <TargetedAction: Summon(CARDS=<HeroPower ('DIE, INSECT!')>)> targeting [Player(name='Player1', hero=<Hero ('Ragnaros the Firelord')>)]
[fireplace.actions]: Player1 summons [<HeroPower ('DIE, INSECT!')>]
[fireplace.card]: <Hero ('Ragnaros the Firelord')> moves from <Zone.SETASIDE: 6> to <Zone.PLAY: 1>
[fireplace.actions]: Processing Death for <Minion ('Slime')>
[fireplace.actions]: <Minion ('Reckless Rocketeer')> attacks <Minion ('Mad Scientist')>
[fireplace.actions]: <Minion ('Reckless Rocketeer')> triggering <TargetedAction: Hit(AMOUNT=5)> targeting [<Minion ('Mad Scientist')>]
[fireplace.actions]: <Minion ('Reckless Rocketeer')> triggering <TargetedAction: Predamage(AMOUNT=5)> targeting [<Minion ('Mad Scientist')>]
[fireplace.actions]: <Minion ('Reckless Rocketeer')> triggering <TargetedAction: Damage(AMOUNT=5)> targeting [<Minion ('Mad Scientist')>]
[fireplace.actions]: <Minion ('Mad Scientist')> triggering <TargetedAction: Hit(AMOUNT=2)> targeting [<Minion ('Reckless Rocketeer')>]
[fireplace.actions]: <Minion ('Mad Scientist')> triggering <TargetedAction: Predamage(AMOUNT=2)> targeting [<Minion ('Reckless Rocketeer')>]
[fireplace.actions]: <Minion ('Mad Scientist')> triggering <TargetedAction: Damage(AMOUNT=2)> targeting [<Minion ('Reckless Rocketeer')>]
[fireplace.game]: Scheduling death for <Minion ('Reckless Rocketeer')>
[fireplace.entity]: <Minion ('Reckless Rocketeer')> is removed from the field
[fireplace.card]: <Minion ('Reckless Rocketeer')> moves from <Zone.PLAY: 1> to <Zone.GRAVEYARD: 4>
[fireplace.game]: Scheduling death for <Minion ('Mad Scientist')>
[fireplace.entity]: <Minion ('Mad Scientist')> is removed from the field
[fireplace.card]: <Minion ('Mad Scientist')> moves from <Zone.PLAY: 1> to <Zone.GRAVEYARD: 4>
[fireplace.actions]: Processing Death for <Minion ('Reckless Rocketeer')>
[fireplace.actions]: Processing Death for <Minion ('Mad Scientist')>
[fireplace.actions]: Game(players=(Player(name='Player1', hero=<Hero ('Ragnaros the Firelord')>), Player(name='Player2', hero=<Hero ('Ragnaros the Firelord')>))) triggering <TargetedAction: Deathrattle()> targeting [<Minion ('Mad Scientist')>]
[fireplace.actions]: <Minion ('Mad Scientist')> triggering <TargetedAction: Summon(CARDS=RANDOM(<DECK Attr(eq(<GameTag.CONTROLLER: 50>, Controller(<SELF>))) + SECRET +>))> targeting [Player(name='Player2', hero=<Hero ('Ragnaros the Firelord')>)]
[fireplace.actions]: Player2 summons []
[fireplace.entity]: Player1 ends turn 33
[fireplace.actions]: <Minion ('Stoneskin Gargoyle')> triggers off <Action: BeginTurn(PLAYER=Player(name='Player2', hero=<Hero ('Ragnaros the Firelord')>))> from Game(players=(Player(name='Player1', hero=<Hero ('Ragnaros the Firelord')>), Player(name='Player2', hero=<Hero ('Ragnaros the Firelord')>)))
[fireplace.actions]: <Minion ('Stoneskin Gargoyle')> triggering <TargetedAction: Heal(AMOUNT=Attr(<SELF>, <GameTag.DAMAGE: 44>))> targeting [<Minion ('Stoneskin Gargoyle')>]
[fireplace.entity]: Player2 begins turn 34
[fireplace.entity]: Player2 is now at 10 mana crystals
[fireplace.actions]: Player(name='Player2', hero=<Hero ('Ragnaros the Firelord')>) triggering <TargetedAction: Draw()> targeting [Player(name='Player2', hero=<Hero ('Ragnaros the Firelord')>)]
[fireplace.entity]: Player2 draws <Minion ('Mountain Giant')>
[fireplace.card]: <Minion ('Mountain Giant')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
[fireplace.actions]: <Minion ('Stoneskin Gargoyle')> attacks <Hero ('Ragnaros the Firelord')>
[fireplace.actions]: <Minion ('Stoneskin Gargoyle')> triggering <TargetedAction: Hit(AMOUNT=1)> targeting [<Hero ('Ragnaros the Firelord')>]
[fireplace.actions]: <Minion ('Stoneskin Gargoyle')> triggering <TargetedAction: Predamage(AMOUNT=1)> targeting [<Hero ('Ragnaros the Firelord')>]
[fireplace.actions]: <Secret ('Ice Block')> triggers off <TargetedAction: Predamage(AMOUNT=1)> from <Minion ('Stoneskin Gargoyle')>
[fireplace.actions]: <Minion ('Stoneskin Gargoyle')> triggering <TargetedAction: Damage(AMOUNT=1)> targeting [<Hero ('Ragnaros the Firelord')>]
[fireplace.actions]: <Minion ('Bolf Ramshield')> attacks <Hero ('Ragnaros the Firelord')>
[fireplace.actions]: <Minion ('Bolf Ramshield')> triggering <TargetedAction: Hit(AMOUNT=3)> targeting [<Hero ('Ragnaros the Firelord')>]
[fireplace.actions]: <Minion ('Bolf Ramshield')> triggering <TargetedAction: Predamage(AMOUNT=3)> targeting [<Hero ('Ragnaros the Firelord')>]
[fireplace.actions]: <Secret ('Ice Block')> triggers off <TargetedAction: Predamage(AMOUNT=3)> from <Minion ('Bolf Ramshield')>
[fireplace.actions]: <Minion ('Bolf Ramshield')> triggering <TargetedAction: Damage(AMOUNT=3)> targeting [<Hero ('Ragnaros the Firelord')>]
[fireplace.entity]: Player2 ends turn 34
[fireplace.entity]: Player1 begins turn 35
[fireplace.entity]: Player1 is now at 10 mana crystals
[fireplace.actions]: Player(name='Player1', hero=<Hero ('Ragnaros the Firelord')>) triggering <TargetedAction: Draw()> targeting [Player(name='Player1', hero=<Hero ('Ragnaros the Firelord')>)]
[fireplace.entity]: Player1 draws <Spell ('Arcane Blast')>
[fireplace.card]: <Spell ('Arcane Blast')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
Playing <Spell ('Arcane Blast')> on <Minion ('Bolf Ramshield')>
[fireplace.entity]: Player1 plays <Spell ('Arcane Blast')>
[fireplace.card]: <Spell ('Arcane Blast')> moves from <Zone.HAND: 3> to <Zone.PLAY: 1>
[fireplace.actions]: <Spell ('Arcane Blast')> triggering <TargetedAction: Battlecry()> targeting [<Spell ('Arcane Blast')>]
[fireplace.actions]: Activating <Spell ('Arcane Blast')> action targeting <Minion ('Bolf Ramshield')>
[fireplace.actions]: <Spell ('Arcane Blast')> triggering <TargetedAction: Hit(AMOUNT=2)> targeting [<Minion ('Bolf Ramshield')>]
[fireplace.actions]: <Spell ('Arcane Blast')> triggering <TargetedAction: Predamage(AMOUNT=4)> targeting [<Minion ('Bolf Ramshield')>]
[fireplace.actions]: <Spell ('Arcane Blast')> triggering <TargetedAction: Damage(AMOUNT=4)> targeting [<Minion ('Bolf Ramshield')>]
[fireplace.entity]: Player1 ends turn 35
[fireplace.actions]: <Minion ('Stoneskin Gargoyle')> triggers off <Action: BeginTurn(PLAYER=Player(name='Player2', hero=<Hero ('Ragnaros the Firelord')>))> from Game(players=(Player(name='Player1', hero=<Hero ('Ragnaros the Firelord')>), Player(name='Player2', hero=<Hero ('Ragnaros the Firelord')>)))
[fireplace.actions]: <Minion ('Stoneskin Gargoyle')> triggering <TargetedAction: Heal(AMOUNT=Attr(<SELF>, <GameTag.DAMAGE: 44>))> targeting [<Minion ('Stoneskin Gargoyle')>]
[fireplace.entity]: Player2 begins turn 36
[fireplace.entity]: Player2 is now at 10 mana crystals
[fireplace.actions]: Player(name='Player2', hero=<Hero ('Ragnaros the Firelord')>) triggering <TargetedAction: Draw()> targeting [Player(name='Player2', hero=<Hero ('Ragnaros the Firelord')>)]
[fireplace.entity]: Player2 draws <Minion ('Injured Blademaster')>
[fireplace.card]: <Minion ('Injured Blademaster')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
[fireplace.entity]: Player2 uses hero power <HeroPower ('DIE, INSECT!')> on None
[fireplace.actions]: <HeroPower ('DIE, INSECT!')> triggering <TargetedAction: Hit(AMOUNT=8)> targeting [<Hero ('Ragnaros the Firelord')>]
[fireplace.actions]: <HeroPower ('DIE, INSECT!')> triggering <TargetedAction: Predamage(AMOUNT=8)> targeting [<Hero ('Ragnaros the Firelord')>]
[fireplace.actions]: <Secret ('Ice Block')> triggers off <TargetedAction: Predamage(AMOUNT=8)> from <HeroPower ('DIE, INSECT!')>
[fireplace.actions]: <Secret ('Ice Block')> triggering <TargetedAction: Reveal()> targeting [<Secret ('Ice Block')>]
[fireplace.actions]: Revealing secret <Secret ('Ice Block')>
[fireplace.card]: <Secret ('Ice Block')> moves from <Zone.SECRET: 7> to <Zone.GRAVEYARD: 4>
[fireplace.actions]: <Secret ('Ice Block')> triggering <TargetedAction: Buff(BUFF='EX1_295o')> targeting [<Hero ('Ragnaros the Firelord')>]
[fireplace.entity]: Applying <Enchantment ('Ice Block')> to <Hero ('Ragnaros the Firelord')>
[fireplace.card]: <Enchantment ('Ice Block')> moves from <Zone.SETASIDE: 6> to <Zone.PLAY: 1>
[fireplace.actions]: <HeroPower ('DIE, INSECT!')> triggering <TargetedAction: Damage(AMOUNT=8)> targeting [<Hero ('Ragnaros the Firelord')>]
[fireplace.entity]: <Hero ('Ragnaros the Firelord')> is immune to 8 damage from <HeroPower ('DIE, INSECT!')>
Playing <Minion ('The Black Knight')> on None
[fireplace.entity]: Player2 plays <Minion ('The Black Knight')>
[fireplace.card]: <Minion ('The Black Knight')> moves from <Zone.HAND: 3> to <Zone.PLAY: 1>
[fireplace.actions]: <Minion ('The Black Knight')> triggering <TargetedAction: Battlecry()> targeting [<Minion ('The Black Knight')>]
[fireplace.actions]: Activating <Minion ('The Black Knight')> action targeting None
[fireplace.actions]: <Minion ('The Black Knight')> triggering <TargetedAction: Destroy()> targeting [None]
Traceback (most recent call last):
  File "./full_game.py", line 90, in <module>
    main()
  File "./full_game.py", line 84, in main
    test_full_game()
  File "./full_game.py", line 72, in test_full_game
    play_full_game()
  File "./full_game.py", line 52, in play_full_game
    card.play(target=target)
  File "../fireplace/card.py", line 274, in play
    self.game.queue_actions(self.controller, [actions.Play(self, target, index)])
  File "../fireplace/game.py", line 160, in queue_actions
    ret = self.trigger_actions(source, actions)
  File "../fireplace/game.py", line 184, in trigger_actions
    ret.append(action.trigger(source))
  File "../fireplace/actions.py", line 138, in trigger
    self.do(source, *args)
  File "../fireplace/actions.py", line 349, in do
    source.game.queue_actions(source_card, [Battlecry(card)])
  File "../fireplace/game.py", line 160, in queue_actions
    ret = self.trigger_actions(source, actions)
  File "../fireplace/game.py", line 184, in trigger_actions
    ret.append(action.trigger(source))
  File "../fireplace/actions.py", line 485, in trigger
    ret.append(self.do(source, target, *target_args))
  File "../fireplace/actions.py", line 602, in do
    source.game.queue_actions(card, actions)
  File "../fireplace/game.py", line 160, in queue_actions
    ret = self.trigger_actions(source, actions)
  File "../fireplace/game.py", line 184, in trigger_actions
    ret.append(action.trigger(source))
  File "../fireplace/actions.py", line 485, in trigger
    ret.append(self.do(source, target, *target_args))
  File "../fireplace/actions.py", line 618, in do
    target._destroy()
AttributeError: 'NoneType' object has no attribute '_destroy'
```

**Comment by jleclanche** [comment]
I don't know what's happening there or why it crashed. I'll just.. close.
