### ISSUE TITLE
Museum Curator: 'CardXML' object has no attribute 'deathrattle'

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#291]
```
AttributeError: 'CardXML' object has no attribute 'deathrattle'
```

[Full log](https://gist.githubusercontent.com/beheh/045710e401dac7f44a8b/raw/da4bfa7d62024cefda6147c41508e673f47a7041/gistfile1.txt).

```
Traceback (most recent call last):
  File "./test_fuzzy.py", line 70, in main
    card.play(target=target, choose=choice)
  File "/home/benedict/Dokumente/fireplace/fireplace/card.py", line 280, in play
    self.game.queue_actions(self.controller, [actions.Play(self, target, index, choose)])
  File "/home/benedict/Dokumente/fireplace/fireplace/game.py", line 142, in queue_actions
    ret = self.trigger_actions(source, actions)
  File "/home/benedict/Dokumente/fireplace/fireplace/game.py", line 166, in trigger_actions
    ret.append(action.trigger(source))
  File "/home/benedict/Dokumente/fireplace/fireplace/actions.py", line 148, in trigger
    self.do(source, *args)
  File "/home/benedict/Dokumente/fireplace/fireplace/actions.py", line 360, in do
    source.game.queue_actions(card, [Battlecry(battlecry_card, card.target)])
  File "/home/benedict/Dokumente/fireplace/fireplace/game.py", line 142, in queue_actions
    ret = self.trigger_actions(source, actions)
  File "/home/benedict/Dokumente/fireplace/fireplace/game.py", line 166, in trigger_actions
    ret.append(action.trigger(source))
  File "/home/benedict/Dokumente/fireplace/fireplace/actions.py", line 493, in trigger
    ret.append(self.do(source, target, *target_args))
  File "/home/benedict/Dokumente/fireplace/fireplace/actions.py", line 625, in do
    source.game.queue_actions(source, actions)
  File "/home/benedict/Dokumente/fireplace/fireplace/game.py", line 142, in queue_actions
    ret = self.trigger_actions(source, actions)
  File "/home/benedict/Dokumente/fireplace/fireplace/game.py", line 166, in trigger_actions
    ret.append(action.trigger(source))
  File "/home/benedict/Dokumente/fireplace/fireplace/actions.py", line 492, in trigger
    target_args = self.get_target_args(source, target)
  File "/home/benedict/Dokumente/fireplace/fireplace/actions.py", line 661, in get_target_args
    cards = picker.evaluate(source, count=3)
  File "/home/benedict/Dokumente/fireplace/fireplace/dsl/random_picker.py", line 46, in evaluate
    cards = self.cards
  File "/home/benedict/Dokumente/fireplace/fireplace/dsl/random_picker.py", line 26, in cards
    self._cards = self._filter_cards(self.filters)
  File "/home/benedict/Dokumente/fireplace/fireplace/dsl/random_picker.py", line 31, in _filter_cards
    return cards.filter(**filters)
  File "/home/benedict/Dokumente/fireplace/fireplace/cards/__init__.py", line 123, in filter
    card for card in cards if (isinstance(value, list) and getattr(card, attr) in value) or
  File "/home/benedict/Dokumente/fireplace/fireplace/cards/__init__.py", line 124, in <listcomp>
    getattr(card, attr) == value
```

**Comment by jleclanche** [comment]
That attribute [exists](https://github.com/HearthSim/python-hearthstone/blob/master/hearthstone/cardxml.py#L167-L169), make sure python-hearthstone is up to date.
