### ISSUE TITLE
full game test fails

### ISSUE THREAD

**Issue by manuel-delverme** [jleclanche/fireplace#424]
```
➜  tests git:(master) ✗ python3.6 full_game.py
[fireplace.__init__]: Initializing card database
[fireplace.__init__]: Merged 2829 cards
[fireplace.entity]: Setting up game Game(players=(Player(name='Player1', hero=None), Player(name='Player2', hero=None)))
[fireplace.entity]: Tossing the coin... Player1 wins!
[fireplace.actions]: Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>) triggering <TargetedAction: Summon(<Summon.CARD>=<Hero ('Jaina Proudmoore')>)> targeting [Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>)]
[fireplace.actions]: Player1 summons [<Hero ('Jaina Proudmoore')>]
[fireplace.entity]: Empty stack, refreshing auras and processing deaths
[fireplace.entity]: Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>) shuffles their deck
[fireplace.card]: <Spell ('Arcane Intellect')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
[fireplace.card]: <Minion ('Faceless Summoner')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
[fireplace.card]: <Spell ('Pyroblast')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
[fireplace.actions]: Player(name='Player2', hero=<Hero ('Garrosh Hellscream')>) triggering <TargetedAction: Summon(<Summon.CARD>=<Hero ('Garrosh Hellscream')>)> targeting [Player(name='Player2', hero=<Hero ('Garrosh Hellscream')>)]
[fireplace.actions]: Player2 summons [<Hero ('Garrosh Hellscream')>]
[fireplace.entity]: Empty stack, refreshing auras and processing deaths
[fireplace.entity]: Player(name='Player2', hero=<Hero ('Garrosh Hellscream')>) shuffles their deck
[fireplace.card]: <Spell ('I Know a Guy')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
[fireplace.card]: <Minion ('Armorsmith')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
[fireplace.card]: <Spell ('Crush')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
[fireplace.card]: <Spell ('Bouncing Blade')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
[fireplace.entity]: Entering mulligan phase
Can mulligan [<Spell ('Arcane Intellect')>, <Minion ('Faceless Summoner')>, <Spell ('Pyroblast')>]
[fireplace.actions]: Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>) triggering <TargetedAction: Draw()> targeting [Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>)]
[fireplace.entity]: Player1 draws <Spell ('Arcane Intellect')>
[fireplace.card]: <Spell ('Arcane Intellect')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
[fireplace.actions]: Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>) triggering <TargetedAction: Draw()> targeting [Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>)]
[fireplace.entity]: Player1 draws <Spell ('Cone of Cold')>
[fireplace.card]: <Spell ('Cone of Cold')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
[fireplace.entity]: Empty stack, refreshing auras and processing deaths
[fireplace.card]: <Minion ('Faceless Summoner')> moves from <Zone.HAND: 3> to <Zone.DECK: 2>
[fireplace.card]: <Spell ('Arcane Intellect')> moves from <Zone.HAND: 3> to <Zone.DECK: 2>
[fireplace.entity]: Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>) shuffles their deck
Can mulligan [<Spell ('I Know a Guy')>, <Minion ('Armorsmith')>, <Spell ('Crush')>, <Spell ('Bouncing Blade')>]
[fireplace.actions]: Player(name='Player2', hero=<Hero ('Garrosh Hellscream')>) triggering <TargetedAction: Draw()> targeting [Player(name='Player2', hero=<Hero ('Garrosh Hellscream')>)]
[fireplace.entity]: Player2 draws <Minion ('Alley Armorsmith')>
[fireplace.card]: <Minion ('Alley Armorsmith')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
[fireplace.actions]: Player(name='Player2', hero=<Hero ('Garrosh Hellscream')>) triggering <TargetedAction: Draw()> targeting [Player(name='Player2', hero=<Hero ('Garrosh Hellscream')>)]
[fireplace.entity]: Player2 draws <Minion ('Iron Juggernaut')>
[fireplace.card]: <Minion ('Iron Juggernaut')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
[fireplace.entity]: Empty stack, refreshing auras and processing deaths
[fireplace.card]: <Minion ('Armorsmith')> moves from <Zone.HAND: 3> to <Zone.DECK: 2>
[fireplace.card]: <Spell ('Crush')> moves from <Zone.HAND: 3> to <Zone.DECK: 2>
[fireplace.entity]: Player(name='Player2', hero=<Hero ('Garrosh Hellscream')>) shuffles their deck
[fireplace.entity]: Player2 gets The Coin (GAME_005)
[fireplace.actions]: Player(name='Player2', hero=<Hero ('Garrosh Hellscream')>) triggering <TargetedAction: Give(<Give.CARD>='GAME_005')> targeting [Player(name='Player2', hero=<Hero ('Garrosh Hellscream')>)]
[fireplace.actions]: Giving [<Spell ('The Coin')>] to Player2
[fireplace.card]: <Spell ('The Coin')> moves from <Zone.SETASIDE: 6> to <Zone.HAND: 3>
[fireplace.entity]: Empty stack, refreshing auras and processing deaths
[fireplace.entity]: Player1 begins turn 1
[fireplace.entity]: Player1 is now at 1 mana crystals
[fireplace.actions]: Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>) triggering <TargetedAction: Draw()> targeting [Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>)]
[fireplace.entity]: Player1 draws <Spell ('Forbidden Flame')>
[fireplace.card]: <Spell ('Forbidden Flame')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
[fireplace.entity]: Empty stack, refreshing auras and processing deaths
Traceback (most recent call last):
  File "full_game.py", line 29, in <module>
    main()
  File "full_game.py", line 25, in main
    test_full_game()
  File "full_game.py", line 10, in test_full_game
    play_full_game()
  File "/home/awok/miniconda3/lib/python3.6/site-packages/fireplace-0.1-py3.6.egg/fireplace/utils.py", line 233, in play_full_game
  File "/home/awok/miniconda3/lib/python3.6/site-packages/fireplace-0.1-py3.6.egg/fireplace/utils.py", line 187, in play_turn
AttributeError: 'NoneType' object has no attribute 'is_usable'

```

**Comment by manuel-delverme** [comment]
hero powers are never set

**Comment by manuel-delverme** [comment]
everything works while running with python3.5; I'm closing this, tell me if you prefer me to look into the python3.6 problem a little more
