### ISSUE TITLE
tests/full_game.py doesn't run

### ISSUE THREAD

**Issue by pkappler** [jleclanche/fireplace#46]
1) Import errors:

>./full_game.py
Traceback (most recent call last):
  File "./full_game.py", line 48, in <module>
    main()
  File "./full_game.py", line 11, in main
    deck1 = randomDraft(hero=fireplace.heroes.MAGE)
AttributeError: 'module' object has no attribute 'heroes'

2) line 17: 'game' variable shadows the module name
3) lines 13,14: Player constructor doesn't accept a deck

I'm submitting a pull request that fixes these problems. The test now runs for 5 turns before throwing this exception.  (I'm brand new to the codebase  - haven't dug deeper.)

> Traceback (most recent call last):
  File "full_game.py", line 53, in <module>
    main()
  File "full_game.py", line 49, in main
    gm.endTurn()
  File "../fireplace/game.py", line 186, in endTurn
    self.broadcast("TURN_END", self.currentPlayer)
  File "../fireplace/game.py", line 209, in broadcast
    super().broadcast(event, *args)
  File "../fireplace/entity.py", line 24, in broadcast
    f(*args)
  File "../fireplace/game.py", line 231, in TURN_END
    player.broadcast("OWN_TURN_END")
  File "../fireplace/player.py", line 260, in broadcast
    super().broadcast(event, *args)
  File "../fireplace/entity.py", line 24, in broadcast
    f(*args)
  File "../fireplace/card.py", line 66, in _func
    self.game.queueActions(self, actions)
  File "../fireplace/game.py", line 138, in queueActions
    action.trigger(source, self)
  File "../fireplace/actions.py", line 31, in trigger
    targets = self.eval(self.target, source, game)
  File "../fireplace/actions.py", line 28, in eval
    return selector.eval(game, source)
  File "../fireplace/targeting.py", line 156, in eval
    result += [e for e in entities if self.test(e, source)]
  File "../fireplace/targeting.py", line 156, in <listcomp>
    result += [e for e in entities if self.test(e, source)]
  File "../fireplace/targeting.py", line 202, in test
    op(self, stack)
  File "../fireplace/targeting.py", line 211, in _and
    b = stack.pop()
IndexError: pop from empty list

**Comment by jleclanche** [comment]
Thanks - Yeah I haven't kept that test up to date. Your PR doesn't fix it properly - I'll get it fixed.

**Comment by jleclanche** [comment]
The "pop from empty list" issue is something else, I'll probably get it fixed in the events revamp (currently in the new-new-new-events branch).

**Comment by jleclanche** [comment]
BTW, we have an irc channel you might want to join if you are interested in fireplace. Details on http://hearthsim.info/ - ping me (jleclanche) if you swing by!
