### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by Ragowit** [jleclanche/fireplace#48]
```
Traceback (most recent call last):
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\mcts\uct.py", line 527, in UCTPlayGame
    m = UCT(rootstate = state, seconds = 10, verbose = False)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\mcts\uct.py", line 497, in UCT
    state.DoMove(random.choice(state.GetMoves()))
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\mcts\uct.py", line 150, in DoMove
    minion.attack(minion.targets[move[3]])
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 368, in attack
    self.game.attack(self, target)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\game.py", line 72, in attack
    return self.queueActions(source, [Attack(source, target)])
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\game.py", line 136, in queueActions
    self._processDeaths()
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\game.py", line 119, in _processDeaths
    self.queueActions(self, actions)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\game.py", line 132, in queueActions
    ret.append(action.trigger(source, self))
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\actions.py", line 87, in trigger
    self.do(source, game, *args)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\actions.py", line 139, in do
    target.zone = Zone.GRAVEYARD
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 75, in zone
    self._setZone(value)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 518, in _setZone
    super()._setZone(value)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 363, in _setZone
    super()._setZone(zone)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 181, in _setZone
    super()._setZone(zone)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 97, in _setZone
    aura.destroy()
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 736, in destroy
    self.game.auras.remove(self)
ValueError: list.remove(x): x not in list
```

```
INFO:root:two ends turn 2
INFO:root:one begins turn 3
INFO:root:one is now at 11 mana crystals
INFO:root:Player(name='one', hero=<Hero ('Jaina Proudmoore')>) triggering <TargetedAction: Draw()> targeting [Player(name='one', hero=<Hero ('Jaina Proudmoore')>)]
INFO:root:one draws <Minion ('Bluegill Warrior')>
DEBUG:root:<Minion ('Bluegill Warrior')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
INFO:root:<Minion ('Raid Leader')> attacks <Minion ('Faerie Dragon')>
INFO:root:<Minion ('Raid Leader')> triggering <TargetedAction: Damage(amount=3)> targeting [<Minion ('Faerie Dragon')>]
INFO:root:<Minion ('Faerie Dragon')> damaged for 3 health
INFO:root:<Minion ('Faerie Dragon')> triggering <TargetedAction: Damage(amount=3)> targeting [<Minion ('Raid Leader')>]
INFO:root:<Minion ('Raid Leader')> damaged for 3 health
INFO:root:Destroying buff <Enchantment ('Enhanced')> from <Minion ('Raid Leader')>
DEBUG:root:<Enchantment ('Enhanced')> moves from <Zone.PLAY: 1> to <Zone.GRAVEYARD: 4>
INFO:root:<Minion ('Raid Leader')> is removed from the field
INFO:root:<Minion ('Raid Leader')> healed for 3 health
DEBUG:root:<Minion ('Raid Leader')> moves from <Zone.PLAY: 1> to <Zone.GRAVEYARD: 4>
INFO:root:Removing <Aura ('CS2_122e')> affecting [<Minion ('Gurubashi Berserker')>, <Minion ('Frostwolf Warlord')>]
```

**Comment by Ragowit** [comment]
Same kind of error occured, but from a morph. I guess I might have to start look into how auras get copied in my fork.

```
Traceback (most recent call last):
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\mcts\uct.py", line 527, in UCTPlayGame
    m = UCT(rootstate = state, seconds = 10, verbose = False)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\mcts\uct.py", line 497, in UCT
    state.DoMove(random.choice(state.GetMoves()))
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\mcts\uct.py", line 145, in DoMove
    card.play()
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 291, in play
    self.controller.play(self, target, choose)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\player.py", line 181, in play
    return self.game.queueActions(self, [Play(card, target, choose)])
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\game.py", line 159, in queueActions
    ret.append(action.trigger(source, self))
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\actions.py", line 87, in trigger
    self.do(source, game, *args)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\actions.py", line 190, in do
    source._play(card)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\player.py", line 199, in _play
    self.summon(card)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\player.py", line 177, in summon
    self.game.queueActions(self, [Summon(self, card)])
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\game.py", line 159, in queueActions
    ret.append(action.trigger(source, self))
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\actions.py", line 235, in trigger
    ret.append(self.do(source, game, *extra_args))
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\actions.py", line 505, in do
    card.summon()
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 603, in summon
    super().summon()
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 187, in summon
    self.action()
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 213, in action
    self.game.queueActions(self, actions)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\game.py", line 159, in queueActions
    ret.append(action.trigger(source, self))
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\actions.py", line 235, in trigger
    ret.append(self.do(source, game, *extra_args))
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\actions.py", line 437, in do
    target.morph(self.id)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 574, in morph
    self.zone = Zone.REMOVEDFROMGAME
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 75, in zone
    self._setZone(value)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 541, in _setZone
    super()._setZone(value)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 383, in _setZone
    super()._setZone(zone)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 180, in _setZone
    super()._setZone(zone)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 97, in _setZone
    aura.destroy()
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 758, in destroy
    self.game.auras.remove(self)
ValueError: list.remove(x): x not in list
```

```
INFO:root:one ends turn 1
INFO:root:two begins turn 2
INFO:root:two is now at 10 mana crystals
INFO:root:Player(name='two', hero=<Hero ('Valeera Sanguinar')>) triggering <TargetedAction: Draw()> targeting [Player(name='two', hero=<Hero ('Valeera Sanguinar')>)]
INFO:root:two overdraws and loses <Minion ('Stoneskin Gargoyle')>!
INFO:root:<Minion ('Stoneskin Gargoyle')> triggering <TargetedAction: Destroy()> targeting [<Minion ('Stoneskin Gargoyle')>]
DEBUG:root:<Minion ('Stoneskin Gargoyle')> moves from <Zone.DECK: 2> to <Zone.GRAVEYARD: 4>
INFO:root:two plays <Minion ('Kezan Mystic')> from their hand
INFO:root:Player(name='two', hero=<Hero ('Valeera Sanguinar')>) triggering <TargetedAction: Summon(card=<Minion ('Kezan Mystic')>)> targeting [Player(name='two', hero=<Hero ('Valeera Sanguinar')>)]
INFO:root:two summons <Minion ('Kezan Mystic')>
INFO:root:Summoning <Minion ('Kezan Mystic')>
DEBUG:root:<Minion ('Kezan Mystic')> moves from <Zone.HAND: 3> to <Zone.PLAY: 1>
INFO:root:Activating <Minion ('Kezan Mystic')> action targeting None
INFO:root:<Minion ('Kezan Mystic')> triggering <TargetedAction: TakeControl()> targeting []
INFO:root:two plays <Minion ('Tinkmaster Overspark')> from their hand
INFO:root:Player(name='two', hero=<Hero ('Valeera Sanguinar')>) triggering <TargetedAction: Summon(card=<Minion ('Tinkmaster Overspark')>)> targeting [Player(name='two', hero=<Hero ('Valeera Sanguinar')>)]
INFO:root:two summons <Minion ('Tinkmaster Overspark')>
INFO:root:Summoning <Minion ('Tinkmaster Overspark')>
DEBUG:root:<Minion ('Tinkmaster Overspark')> moves from <Zone.HAND: 3> to <Zone.PLAY: 1>
INFO:root:Activating <Minion ('Tinkmaster Overspark')> action targeting None
INFO:root:<Minion ('Tinkmaster Overspark')> triggering <TargetedAction: Morph(id='EX1_tk28')> targeting [<Minion ('Raid Leader')>]
INFO:root:Morphing <Minion ('Raid Leader')> into <Minion ('Squirrel')>
INFO:root:<Minion ('Raid Leader')> is removed from the field
DEBUG:root:<Minion ('Raid Leader')> moves from <Zone.PLAY: 1> to <Zone.REMOVEDFROMGAME: 5>
INFO:root:Removing <Aura ('CS2_122e')> affecting [<Minion ('Kobold Geomancer')>, <Minion ('Lord of the Arena')>]
```

**Comment by Ragowit** [comment]
From time to time I like to merge in your changes to my fork to see if anything might have happened that solves my problem. Sadly, it has not (this might be expected since no work has been done with auras?). But I guess it has something to do with my copy/clone function, that debug line "begins turn 1, is now at 10 mana crystals" doesn't feel quite right. From my latest run:

```
Traceback (most recent call last):
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\mcts\uct.py", line 532, in UCTPlayGame
    m = UCT(rootstate = state, seconds = 10, verbose = False)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\mcts\uct.py", line 502, in UCT
    state.DoMove(random.choice(state.GetMoves()))
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\mcts\uct.py", line 155, in DoMove
    minion.attack(minion.targets[move[3]])
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 374, in attack
    self.game.attack(self, target)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\game.py", line 80, in attack
    return self.queue_actions(source, [Attack(source, target)])
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\game.py", line 193, in queue_actions
    self.process_deaths()
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\game.py", line 160, in process_deaths
    self.queue_actions(self, actions)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\game.py", line 189, in queue_actions
    ret.append(action.trigger(source, self))
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\actions.py", line 153, in trigger
    self.do(source, game, *args)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\actions.py", line 205, in do
    target.zone = Zone.GRAVEYARD
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 75, in zone
    self._set_zone(value)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 537, in _set_zone
    super()._set_zone(value)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 369, in _set_zone
    super()._set_zone(zone)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 180, in _set_zone
    super()._set_zone(zone)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 97, in _set_zone
    aura.destroy()
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 754, in destroy
    self.game.auras.remove(self)
ValueError: list.remove(x): x not in list
```

```
INFO:root:Player(name='two', hero=<Hero ('Uther Lightbringer')>) shuffles their deck
INFO:root:Tossing the coin... one wins!
INFO:root:Player(name='one', hero=<Hero ('Jaina Proudmoore')>) triggering <TargetedAction: Draw()> targeting [Player(name='one', hero=<Hero ('Jaina Proudmoore')>)]
INFO:root:one draws <Minion ('Frostwolf Grunt')>
DEBUG:root:<Minion ('Frostwolf Grunt')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
INFO:root:Player(name='one', hero=<Hero ('Jaina Proudmoore')>) triggering <TargetedAction: Draw()> targeting [Player(name='one', hero=<Hero ('Jaina Proudmoore')>)]
INFO:root:one draws <Spell ('Fireball')>
DEBUG:root:<Spell ('Fireball')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
INFO:root:Player(name='one', hero=<Hero ('Jaina Proudmoore')>) triggering <TargetedAction: Draw()> targeting [Player(name='one', hero=<Hero ('Jaina Proudmoore')>)]
INFO:root:one draws <Minion ('Gurubashi Berserker')>
DEBUG:root:<Minion ('Gurubashi Berserker')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
INFO:root:Player(name='two', hero=<Hero ('Uther Lightbringer')>) triggering <TargetedAction: Draw()> targeting [Player(name='two', hero=<Hero ('Uther Lightbringer')>)]
INFO:root:two draws <Minion ('Murloc Raider')>
DEBUG:root:<Minion ('Murloc Raider')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
INFO:root:Player(name='two', hero=<Hero ('Uther Lightbringer')>) triggering <TargetedAction: Draw()> targeting [Player(name='two', hero=<Hero ('Uther Lightbringer')>)]
INFO:root:two draws <Minion ('Blood Knight')>
DEBUG:root:<Minion ('Blood Knight')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
INFO:root:Player(name='two', hero=<Hero ('Uther Lightbringer')>) triggering <TargetedAction: Draw()> targeting [Player(name='two', hero=<Hero ('Uther Lightbringer')>)]
INFO:root:two overdraws and loses <Minion ('Nozdormu')>!
INFO:root:<Minion ('Nozdormu')> triggering <TargetedAction: Destroy()> targeting [<Minion ('Nozdormu')>]
DEBUG:root:<Minion ('Nozdormu')> moves from <Zone.DECK: 2> to <Zone.GRAVEYARD: 4>
INFO:root:Player(name='two', hero=<Hero ('Uther Lightbringer')>) triggering <TargetedAction: Draw()> targeting [Player(name='two', hero=<Hero ('Uther Lightbringer')>)]
INFO:root:two overdraws and loses <Minion ('Alarm-o-Bot')>!
INFO:root:<Minion ('Alarm-o-Bot')> triggering <TargetedAction: Destroy()> targeting [<Minion ('Alarm-o-Bot')>]
DEBUG:root:<Minion ('Alarm-o-Bot')> moves from <Zone.DECK: 2> to <Zone.GRAVEYARD: 4>
INFO:root:one begins turn 1
INFO:root:one is now at 10 mana crystals
INFO:root:Player(name='one', hero=<Hero ('Jaina Proudmoore')>) triggering <TargetedAction: Draw()> targeting [Player(name='one', hero=<Hero ('Jaina Proudmoore')>)]
INFO:root:one draws <Spell ('Fireball')>
DEBUG:root:<Spell ('Fireball')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
INFO:root:two gets The Coin (GAME_005)
INFO:root:Player(name='two', hero=<Hero ('Uther Lightbringer')>) triggering <TargetedAction: Give(card='GAME_005')> targeting [Player(name='two', hero=<Hero ('Uther Lightbringer')>)]
DEBUG:root:Giving [<Spell ('The Coin')>] to two
DEBUG:root:<Spell ('The Coin')> moves from <Zone.INVALID: 0> to <Zone.HAND: 3>
INFO:root:Entering mulligan phase
INFO:root:one plays <Spell ('Fireball')>
INFO:root:Player(name='one', hero=<Hero ('Jaina Proudmoore')>) triggering <TargetedAction: Summon(card=<Spell ('Fireball')>)> targeting [Player(name='one', hero=<Hero ('Jaina Proudmoore')>)]
INFO:root:one summons [<Spell ('Fireball')>]
INFO:root:Summoning <Spell ('Fireball')>
DEBUG:root:<Spell ('Fireball')> moves from <Zone.HAND: 3> to <Zone.PLAY: 1>
INFO:root:Activating <Spell ('Fireball')> action targeting <Minion ('Nefarian')>
INFO:root:<Spell ('Fireball')> triggering <TargetedAction: Hit(amount=6)> targeting [<Minion ('Nefarian')>]
INFO:root:<Spell ('Fireball')> triggering <TargetedAction: Damage(amount=6)> targeting [<Minion ('Nefarian')>]
INFO:root:<Minion ('Nefarian')> damaged for 6 health
INFO:root:<Minion ('Nefarian')> is removed from the field
INFO:root:<Minion ('Nefarian')> healed for 8 health
DEBUG:root:<Minion ('Nefarian')> moves from <Zone.PLAY: 1> to <Zone.GRAVEYARD: 4>
INFO:root:<Minion ('Grimscale Oracle')> attacks <Minion ('King Mukla')>
INFO:root:<Minion ('Grimscale Oracle')> triggering <TargetedAction: Damage(amount=1)> targeting [<Minion ('King Mukla')>]
INFO:root:<Minion ('King Mukla')> damaged for 1 health
INFO:root:<Minion ('King Mukla')> triggering <TargetedAction: Damage(amount=5)> targeting [<Minion ('Grimscale Oracle')>]
INFO:root:<Minion ('Grimscale Oracle')> damaged for 5 health
INFO:root:<Minion ('Grimscale Oracle')> is removed from the field
INFO:root:<Minion ('Grimscale Oracle')> healed for 5 health
DEBUG:root:<Minion ('Grimscale Oracle')> moves from <Zone.PLAY: 1> to <Zone.GRAVEYARD: 4>
INFO:root:Removing <Aura ('EX1_508o')> affecting []
```

**Comment by Ragowit** [comment]
I might have found the solution for my problem. Previously I created new Game-object but the players were still the same. So the Game was new and fresh, but players still had their hand, field and secrets from before.
So I simply create new players when I need and now it seems to work. I will close the issue.
