### ISSUE TITLE
Lord Jaraxxus: 'Minion' object has no attribute 'removeFromField'

### ISSUE THREAD

**Issue by Ragowit** [jleclanche/fireplace#72]
```
INFO:root:one ends turn 25
INFO:root:two begins turn 26
INFO:root:two is now at 10 mana crystals
INFO:root:Player(name='two', hero=<Hero ("Gul'dan")>) triggering <TargetedAction: Draw()> targeting [Player(name='two', hero=<Hero ("Gul'dan")>)]
INFO:root:two draws <Minion ('Voidwalker')>
DEBUG:root:<Minion ('Voidwalker')> moves from <Zone.DECK: 2> to <Zone.HAND: 3>
INFO:root:<Minion ('Bloodfen Raptor')> attacks <Minion ('Archmage')>
INFO:root:<Minion ('Bloodfen Raptor')> triggering <TargetedAction: Damage(amount=3)> targeting [<Minion ('Archmage')>]
INFO:root:<Minion ('Archmage')> damaged for 3 health
INFO:root:<Minion ('Archmage')> triggering <TargetedAction: Damage(amount=4)> targeting [<Minion ('Bloodfen Raptor')>]
INFO:root:<Minion ('Bloodfen Raptor')> damaged for 4 health
DEBUG:root:Scheduling death for <Minion ('Bloodfen Raptor')>
INFO:root:<Minion ('Bloodfen Raptor')> is removed from the field
INFO:root:<Minion ('Bloodfen Raptor')> healed for 4 health
DEBUG:root:<Minion ('Bloodfen Raptor')> moves from <Zone.PLAY: 1> to <Zone.GRAVEYARD: 4>
INFO:root:two plays <Minion ('Lord Jaraxxus')>
INFO:root:Player(name='two', hero=<Hero ("Gul'dan")>) triggering <TargetedAction: Summon(card=<Minion ('Lord Jaraxxus')>)> targeting [Player(name='two', hero=<Hero ("Gul'dan")>)]
INFO:root:two summons [<Minion ('Lord Jaraxxus')>]
INFO:root:Summoning <Minion ('Lord Jaraxxus')>
DEBUG:root:<Minion ('Lord Jaraxxus')> moves from <Zone.HAND: 3> to <Zone.PLAY: 1>
INFO:root:Activating <Minion ('Lord Jaraxxus')> action targeting None
```

```
Traceback (most recent call last):
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\mcts\uct.py", line 524, in UCTPlayGame
    m = UCT(rootstate = state, seconds = 60, verbose = False)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\mcts\uct.py", line 494, in UCT
    state.DoMove(random.choice(state.GetMoves()))
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\mcts\uct.py", line 142, in DoMove
    card.play()
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 288, in play
    self.game.queue_actions(self.controller, [Play(self, target, choose)])
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\game.py", line 187, in queue_actions
    ret.append(action.trigger(source, self))
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\actions.py", line 215, in trigger
    self.do(source, game, *args)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\actions.py", line 316, in do
    game.play(card)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\game.py", line 121, in play
    player.summon(card)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\player.py", line 175, in summon
    self.game.queue_actions(self, [Summon(self, card)])
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\game.py", line 187, in queue_actions
    ret.append(action.trigger(source, self))
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\actions.py", line 365, in trigger
    ret.append(self.do(source, game, *extra_args))
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\actions.py", line 667, in do
    card.summon()
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 591, in summon
    super().summon()
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 188, in summon
    self.action()
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\card.py", line 211, in action
    actions = actions(self, **kwargs)
  File "C:\Users\Ragowit\Documents\GitHub\fireplace\fireplace\cards\classic\warlock.py", line 75, in action
    self.removeFromField()
AttributeError: 'Minion' object has no attribute 'removeFromField'
```

**Comment by beheh** [comment]
Test case:
```
def test_jaraxxus():
	game = prepare_game(WARRIOR, WARRIOR)
	game.player1.hero.power.use()
	game.player1.give("CS2_106").play()
	assert game.player1.weapon.id == "CS2_106"
	game.end_turn(); game.end_turn()

	assert game.player1.hero.health == 30
	assert game.player1.hero.armor == 2
	game.player1.give("EX1_323").play()
	assert game.player1.weapon.id == "EX1_323w"
	assert game.player1.hero.health == 15
	assert game.player1.hero.armor == 0
```
