### ISSUE TITLE
Trade Prince Gallywix: Both players receive Gallywix's coin

### ISSUE THREAD

**Issue by beheh** [jleclanche/fireplace#78]
Trade Prince Gallywix seems to give both players a Gallywix coin whenever the opponent casts a spell (correct behaviour would be: give a copy to the owning player and a Gallywix coin to the opponent).

I've implemented a basic test at beheh/fireplace@161276801ee6cf85d6555b575317f049bf70ee58 and receive the following output (note that THE_COIN is just the test spell, not a Gallywix coin):

```
DEBUG:root:Giving [<Spell ('The Coin')>] to Player1
DEBUG:root:<Spell ('The Coin')> moves from <Zone.INVALID: 0> to <Zone.HAND: 3>
INFO:root:Player1 plays <Spell ('The Coin')>
DEBUG:root:<Spell ('The Coin')> moves from <Zone.HAND: 3> to <Zone.PLAY: 1>
INFO:root:<Minion ('Trade Prince Gallywix')> triggers off <Action: Play(PLAYER=<Spell ('The Coin')>, CARD=None, TARGET=None)> from Player(name='Player1', hero=<Hero ('Uther Lightbringer')>)
INFO:root:<Minion ('Trade Prince Gallywix')> triggering <TargetedAction: Give(CARDS=Copy(<Args.CARD: 1>))> targeting [Player(name='Player1', hero=<Hero ('Uther Lightbringer')>)]
DEBUG:root:Giving [<Spell ('The Coin')>] to Player1
DEBUG:root:<Spell ('The Coin')> moves from <Zone.INVALID: 0> to <Zone.HAND: 3>
INFO:root:<Minion ('Trade Prince Gallywix')> triggering <TargetedAction: Give(CARDS='GVG_028t')> targeting [Player(name='Player1', hero=<Hero ('Uther Lightbringer')>), Player(name='Player2', hero=<Hero ('Rexxar')>)]
DEBUG:root:Giving [<Spell ("Gallywix's Coin")>] to Player1
DEBUG:root:<Spell ("Gallywix's Coin")> moves from <Zone.INVALID: 0> to <Zone.HAND: 3>
DEBUG:root:Giving [<Spell ("Gallywix's Coin")>] to Player2
DEBUG:root:<Spell ("Gallywix's Coin")> moves from <Zone.INVALID: 0> to <Zone.HAND: 3>
INFO:root:Activating <Spell ('The Coin')> action targeting None
INFO:root:<Spell ('The Coin')> triggering <TargetedAction: ManaThisTurn(AMOUNT=1)> targeting [Player(name='Player1', hero=<Hero ('Uther Lightbringer')>)]
Traceback (most recent call last):
  File "test_main.py", line 4559, in <module>
    main()
  File "test_main.py", line 4554, in main
    f()
  File "test_main.py", line 4530, in test_gallywix
    assert len(game.current_player.hand) == 1
AssertionError
```

**Comment by jleclanche** [comment]
It looks like I have the player and opponent switch. Are you sure they *both* get the coin and it's not just the wrong way around?

**Comment by beheh** [comment]
Well, that's what I deduced from the log, specifically:
```
DEBUG:root:Giving [<Spell ("Gallywix's Coin")>] to Player1
DEBUG:root:<Spell ("Gallywix's Coin")> moves from <Zone.INVALID: 0> to <Zone.HAND: 3>
DEBUG:root:Giving [<Spell ("Gallywix's Coin")>] to Player2
DEBUG:root:<Spell ("Gallywix's Coin")> moves from <Zone.INVALID: 0> to <Zone.HAND: 3>
```
