### ISSUE TITLE
Revenge issue?

### ISSUE THREAD

**Issue by jleclanche** [jleclanche/fireplace#98]
```pytb
INFO:root:Player2 plays <Spell ('Revenge')>
DEBUG:root:<Spell ('Revenge')> moves from <Zone.HAND: 3> to <Zone.PLAY: 1>
INFO:root:<Minion ('Lorewalker Cho')> triggers off <Action: Play(PLAYER=<Spell ('Revenge')>, CARD=None, TARGET=None)> from Player(name='Player2', hero=<Hero ('Garrosh Hellscream')>)
INFO:root:<Minion ('Lorewalker Cho')> triggering <TargetedAction: Give(CARDS='BRM_015')> targeting [Player(name='Player1', hero=<Hero ('Jaina Proudmoore')>)]
DEBUG:root:Giving [<Spell ('Revenge')>] to Player1
DEBUG:root:<Spell ('Revenge')> moves from <Zone.INVALID: 0> to <Zone.HAND: 3>
INFO:root:Activating <Spell ('Revenge')> action targeting None
INFO:root:<Spell ('Revenge')> triggering <TargetedAction: Hit(AMOUNT=1)> targeting [None]
Traceback (most recent call last):
  File "./full_game.py", line 54, in <module>
    main()
  File "./full_game.py", line 41, in main
    card.play()
  File "../fireplace/card.py", line 312, in play
    self.game.queue_actions(self.controller, [Play(self, target, choose)])
  File "../fireplace/game.py", line 195, in queue_actions
    ret.append(action.trigger(source))
  File "../fireplace/actions.py", line 108, in trigger
    self.do(source, *args)
  File "../fireplace/actions.py", line 231, in do
    card.action()
  File "../fireplace/card.py", line 224, in action
    self.game.queue_actions(self, actions)
  File "../fireplace/game.py", line 195, in queue_actions
    ret.append(action.trigger(source))
  File "../fireplace/dsl/evaluator.py", line 33, in trigger
    action.trigger(source)
  File "../fireplace/actions.py", line 314, in trigger
    ret.append(self.do(source, target, *target_args))
  File "../fireplace/actions.py", line 490, in do
    attack_source.hit(target, amount)
  File "../fireplace/card.py", line 629, in hit
    super().hit(target, amount)
  File "../fireplace/card.py", line 274, in hit
    return self.game.queue_actions(self, [Damage(target, amount)])
  File "../fireplace/game.py", line 195, in queue_actions
    ret.append(action.trigger(source))
  File "../fireplace/actions.py", line 308, in trigger
    targets = self.get_targets(source, args[0])
  File "../fireplace/actions.py", line 298, in get_targets
    return t.eval(source.game, source)
AttributeError: 'NoneType' object has no attribute 'eval'
```

**Comment by beheh** [comment]
Incoming PR.
